
  name: gerenciadorcs
  version: '4.0'
  summary: Um gerenciador de contas e senhas
  description: |
    O gerenciador de Contas e Senhas é uma plataforma onde usuários podem armazenar contas, usuários e senhas de forma segura. Toda informação fica criptografada no computador do usuário. Este programa não se conecta a internet, não armazena dados em núvem e não coleta informações privadas.
   
  confinement: strict
  base: core24
  
  platforms:
    amd64:
      build-on: [amd64]
      build-for: [amd64]

  parts:
    gerenciadorcs:
      plugin: python
      source: https://github.com/JunioDamasceno/gerenciadorcs.git
      source-subdir: gerenciadorcs  # Aponta para o subdiretório com o código
      stage-packages:
        - python3
        - gir1.2-gtk-3.0
        - python3-gi
        - libxapp-gtk3-module
      build-packages:
        - libgtk-4-dev 
        - libgtk-3-dev
        - libgtk2.0-dev
      override-build: |
      # Copia o bin/start para o diretório de instalação
        install -Dm755 $CRAFT_PROJECT_DIR/bin/start $CRAFT_PART_INSTALL/bin/start
      # Continua com o build padrão do plugin Python
        python -m pip install -e $CRAFT_PART_SRC --prefix $CRAFT_PART_INSTALL/usr
        
  apps:
    gerenciadorcs:
      command: bin/start
      extensions: [gnome]
      plugs:
      - desktop
      - wayland
      - x11
  
