
  name: gerenciadorcs
  version: '2.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Um gerenciador de contas e senhas
  description: |
    O gerenciador de Contas e Senhas é uma plataforma onde usuários podem
    armazenar contas e senhas de forma segura. Toda informação fica criptografada
    no computador do usuário. Este programa não se conecta a internet, não armazena
    dados em núvem e não coleta informações privadas.
   
  confinement: devmode
  base: core18
  
  architectures:
  - build-on: amd64
  - build-on: i386
  
  plugs:
    gerenciadorcs:
    interface: system-files
      write:
      - /snap/gerenciadorcs/current/bin/ac.bin
      - /snap/gerenciadorcs/current/bin/se.bin
      - /snap/gerenciadorcs/current/bin/sx.bin
      - /snap/gerenciadorcs/current/bin/ux.bin
      - /snap/gerenciadorcs/current/bin/asu.bin
      - /snap/gerenciadorcs/current/bin/nu.bin

  parts:
    gerenciadorcs:
      plugin: python
      python-version: python3
      source: https://github.com/JunioDamasceno/gerenciadorcs.git
      stage-packages:
        - python3
        - gir1.2-gtk-3.0
        - python3-gi
      build-packages:
        - libgtk-3-dev
        - libgtk2.0-dev
        
  apps:
    gerenciadorcs:
      command: python3.6 /snap/gerenciadorcs/current/lib/python3.6/site-packages/gerenciadorcs/gerenciadorcs.py
      extensions: [gnome-3-28]
  
