
  name: gerenciadorcs
  version: '2.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Um gerenciador de contas e senhas
  description: |
    O gerenciador de Contas e Senhas é uma plataforma onde usuários podem
    armazenar contas e senhas de forma segura. Toda informação fica criptografada
    no computador do usuário. Este programa não se conecta a internet, não armazena
    dados em núvem e não coleta informações privadas.
   
  confinement: devmode
  base: core18
  
  architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf

  parts:
    gerenciadorcs:
      plugin: python
      python-version: python3
      source: https://github.com/JunioDamasceno/gerenciadorcs.git
      stage-packages:
        - python3-gi
        - libcanberra-gtk3-module
        - gir1.2-gtk-3.0
  apps:
    gerenciadorcs:
      command: python3.6 gerenciadorcs/gerenciadorcs.py
      desktop: gerenciadorcs/gerenciadorcs.desktop
  
