
  name: gerenciadorcs
  version: '4.0'
  summary: Um gerenciador de contas e senhas
  description: |
    O gerenciador de Contas e Senhas é uma plataforma onde usuários podem armazenar contas, usuários e senhas de forma segura. Toda informação fica criptografada no computador do usuário. Este programa não se conecta a internet, não armazena dados em núvem e não coleta informações privadas.
   
  confinement: strict
  base: core22
  
  platforms:
    amd64:
      build-on: [amd64]
      build-for: [amd64]

  parts:
    gerenciadorcs:
      plugin: python
      source: https://github.com/JunioDamasceno/gerenciadorcs.git
      source-subdir: gerenciadorcs  # Aponta para o subdiretório com o código
      stage-packages:
        - python3
        - python3-minimal
        - libpython3-stdlib
        - gir1.2-gtk-3.0
        - python3-gi
      build-packages:
        - libgtk-4-dev 
        - libgtk-3-dev
        - libgtk2.0-dev
      
  apps:
    gerenciadorcs:
      command: python3 $SNAP/gerenciadorcs/gerenciadorcs.py
      extensions: [gnome]
      plugs:
        - desktop
        - wayland
        - x11
  
