name: gerenciadorcs
version: '4.0'
summary: Um gerenciador de contas e senhas
description: |
  Gerenciador de Contas e Senhas seguro e offline.
   
confinement: strict
base: core22

parts:
  gerenciadorcs:
    plugin: python
    source: https://github.com/JunioDamasceno/gerenciadorcs.git
    # Removido o source-subdir para que o plugin encontre o setup.py na raiz
    build-packages:
      - libgirepository1.0-dev
      - pkg-config
    stage-packages:
      - python3-gi
      - gir1.2-gtk-3.0

apps:
  gerenciadorcs:
    extensions: [gnome]
    # Se o setup.py define um console_script chamado 'gerenciadorcs':
    # command: bin/gerenciadorcs 
    # Ou, se quiser chamar o script diretamente:
    command: python3 $SNAP/gerenciadorcs/gerenciadorcs.py
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home  # Adicionado para permitir salvar o banco de dados local
